lab_1/urls.py
from django.urls import re_path
from .views import index
from .views import index, message_post
from .views import index, message_post, message_table  
#url for app
app_name = 'lab_1'
urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^message_post', message_post, name='message_post'),
    re_path(r'^result_table', message_table, name='result_table')

]

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

lab_4/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

lab_5/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

landing_page/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

my_experience/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_1.views import index as index_lab1
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^landing_page/', include('landing_page.urls')),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^lab-4/', include('lab_4.urls')),
    re_path(r'^lab-5/', include('lab_5.urls')),
    re_path(r'^my_experience/', include('my_experience.urls')),
    re_path(r'^$', index_lab1, name='index')
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_1/models.py
from django.db import models
class Message(models.Model):
    name = models.CharField(max_length=27) 
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    
    def str (self): 
        return self.message

lab_2/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

lab_5/models.py
from django.db import models

# Create your models here.

landing_page/models.py
from django.db import models

# Create your models here.

my_experience/models.py
from django.db import models

# Create your models here.

lab_1/forms.py
from django import forms
class Message_Form(forms.Form): 
     error_messages = {
         'required': 'Tolong isi input ini', 
         'invalid': 'Isi input dengan email',
     }

     attrs = { 
         'class': 'form-control'
     }

     name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
     email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
     message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message

# Enter your name here
mhs_name = 'Abdul Azis Ansori' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1998,4,15) #TODO Implement this, format (Year, Month, Date)
pondok_mhs = 'INNAYATULLAH'
univ = 'UTY'
npm = 5170311053 # TODO Implement this

# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm ,'pondok':pondok_mhs, 'univ':univ}
    response['message_form'] = Message_Form
    return render(request, 'index_lab1.html', response)
def table(request):
    response = {'name': 'Message'}
    response['message'] = messages
    return render(request, 'table.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0
def message_post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
       response = {}
       response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
       response['email'] = request.POST['email'] if request.POST['email']!= "" else "Anonymous"
       response['message'] = request.POST['message']
       message = Message(name=response['name'], email=response['email'], 
       message=response['message'])
       message.save()
       html ='form_result.html'
       return render(request, html, response)
    else:
       return HttpResponseRedirect('/')
def message_table(request):
    response = {}
    message = Message.objects.all() 
    response['message'] = message 
    html = 'table.html'
    return render(request, html , response)

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

lab_4/views.py
from django.shortcuts import render

# Biodata
name_mhs = 'ABDUL AZIS ANSORI'
univ_mhs = 'UTY'
pondok_mhs = 'INNAYATULLAH'
# Create your views here.
def index(request):
	response = {'nama':name_mhs, 'univ':univ_mhs, 'pondok':pondok_mhs }
	return render(request, 'lab_4.html', response)

lab_5/views.py
from django.shortcuts import render

# Biodata
name_mhs = 'ABDUL AZIS ANSORI'
univ_mhs = 'UTY'
pondok_mhs = 'INNAYATULLAH'
# Create your views here.
def index(request):
	response = {'nama':name_mhs, 'univ':univ_mhs, 'pondok':pondok_mhs }
	return render(request, 'lab_5.html', response)

landing_page/views.py
from django.shortcuts import render

# Biodata
name_mhs = 'ABDUL AZIS ANSORI'
univ_mhs = 'UTY'
pondok_mhs = 'INNAYATULLAH'
# Create your views here.
def index(request):
	response = {'nama':name_mhs, 'univ':univ_mhs, 'pondok':pondok_mhs }
	return render(request, 'index_lp.html', response)

my_experience/views.py
from django.shortcuts import render

# Biodata
name_mhs = 'ABDUL AZIS ANSORI'
univ_mhs = 'UTY'
pondok_mhs = 'INNAYATULLAH'
# Create your views here.
def index(request):
	response = {'nama':name_mhs, 'univ':univ_mhs, 'pondok':pondok_mhs }
	return render(request, 'index_ex.html', response)

lab_1/templates/form_result.html
{% extends "layout/base.html" %}

{% block content %}

<div class="jumbotron text-center">
			<h1>Pesan Terkirim</h1>
			<p> Pesan dari {{ name }} </p> 
		</div>

<!-- {% block title %}{% endblock %} -->

<textarea readonly rows="15" class="form-control">&quot;{{message}}&quot;- {{name}}
	by {{ email }}
</textarea>
<div style="clear: both;"></div>
{% endblock %}

lab_1/templates/index_lab1.html
{% block content %}

  {% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="{% static 'css/style_lp.css'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Abdul Azis Ansori</title>

  </head>
  <body>
    <style type="text/css">
     #card{
      padding-top: 10px;
     }
     .atas{
  border: 2px solid #253E4F;
  border-radius: 5px;
  margin-top: 50px;
  margin-bottom: 50px;
}
  </style>
    <div class="container atas" >
      <div class="row" id="card">
       <div class="col-sm-3 text-center">
       <img src="{% static 'img/5170311053.jpg'%}" width="100" height="150" >
                  <h6>{{name}}</h6> 
                    <h6>I am {{age}} years old</h6>
                  <h6>{{univ}} || {{pondok}}</h6>
    </div>
    <div class="col-sm-7">
      <h3><b>az-port.herokuapp.com</b></h3>
              <p>saya sangat suka berada di depan laptop. untuk bermain dan coding, saya seorang mahasiswa sistem informasi di salah satu kampus swasta ternama di yogyakarta yaitu Universitas Teknologi Yogyakarta</p>
              <b>more from me ?</b>
    <div class="row">
      <div class="col-sm-4">
     <a href="/my_experience/" class="btn btn-primary">Resume</a>
      </div>
      <div class="col-sm-4">
      <a href="/landing_page/" class="btn btn-primary">Portofolio</a>
      </div>
    </div>

    </div>
    <div class="col-sm">
      <ul >
             <li><a href="https://www.facebook.com/uzumakiaann?ref=bookmarks">Facebook</a></li>
             <li><a href="https://www.instagram.com/azis115_/">Instagram</a></li>
             <li><a href="https://api.whatsapp.com/send?phone=089674552593">Whatsapp</a></li>
              <li><a href="mailto:azisaan552@gmail.com">Email</a></li>
           </ul>

    </div>
    <div class="container">
    <div class="row">
      <div class="col">
         </section>
    <section name="form">

      <h3>Send Message</h3>
          <form id="form" method="POST" action="{% url 'lab_1:message_post' %}">
          {% csrf_token %}
          {{message_form}}

          <br>
          <button type="submit" class="btn btn-primary" >Submit</button>
      </form>

    </section>
    <br>
    </div>
      </div>
    </div>
      </div>
    
    </div>

   

   
    


   

    

    <!-- card -->

          {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

lab_1/templates/layout/base.html
<!DOCTYPE html>
{% include "partials/header.html" %}

{% block content %} {% endblock %}

{% include "partials/footer.html" %}

lab_1/templates/layout/bash.html
<!DOCTYPE html>
{% include "partials/header.html" %}

{% block content %} {% endblock %}

{% include "partials/footer.html" %}

lab_1/templates/partials/footer.html
</section>
	<div class="footer" >
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <p>Copyright<span style="font-size: 20px;">&copy;</span> 2019 | by <a href="https://www.facebook.com/uzumakiaann?ref=bookmarks">Abdul Azis Ansori</a></p>
            
          </div>
          
        </div>
        
      </div>
    </div>
</body>
</html>

<style >
  html{
    position: relative;
  }
	.footer{
		background-color: #333;

	}
	.footer p{
	color: #aaa;
	font-size: 0.9em;
}

</style>

lab_1/templates/partials/header.html
<!-- {% block header %} -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ name }}</title>
    {% load staticfiles %}
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
	<div>
	
   <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
  
  <a class="navbar-brand" href="/lab-1/">My Portofolio</a>
  
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
     
      <li class="nav-item">
       <a class="nav-link" href="/landing_page/">Portofolio</a>
      </li>    
      <li class="nav-item">
       <a class="nav-link" href="/my_experience/">Resume</a>
      </li>    
      <li class="nav-item">
        <a class="nav-link" href="{% url 'lab_1:result_table' %}">Message</a>
      </li>    
    </ul>
  </div>
</div>
</nav>
</div>

<style >
	html{
		position: relative;
	}
</style>







<!-- {% endblock %} -->

lab_1/templates/table.html
{% extends "layout/base.html" %}
{% block content %}
<!-- Populate semua isi pesan dari model -->
<div>
<div class="container" style="margin-top:  60px;">
<table class="table table-bordered" style="position: relative;">
	<thead class="thead-dark">
		<th>Nama</th>
		<th>Email</th>
		<th>Pesan</th>
		<th>Dibuat Pada</th>
	</thead>

	<tbody>
	<!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
		{% for i in message %}
		{% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
		<tr style="  background-color: #eee;"> {% else %} <tr class="success">
			{% endif %}
			<td> {{i.name}} </td>
			<td> {{i.email}} </td>
			<td> {{i.message}} </td>
			<td> {{i.created_date}} </td>
		</tr>
		{% endfor %}
	</tbody>
</table>
</div>
</div>
<div style="clear: both;"></div>
{% endblock %}
<style >
	th {
  background-color: #4CAF50;
  color: white;
}
</style>

lab_4/templates/lab_4.html
{% extends "layout/base.html" %}
{% block content %}
{% load static %}
 <link rel="stylesheet" href="{% static 'css/style_4.css'%}">

<!-- ChatBox Section -->


<body>
	<div class="container">
		<h2>Chat Box</h2>
		<div id="tempatChat">
			
		</div>
		<div class="form">
			<form method="post" id="formProses">
				<div id="error"><span id="spanMesage"></span></div>
				<input type="text" name="chat" id="chat">
				<input type="submit" name="submit" id="submit_chat" value="Balas">
			</form>
		</div>	
	</div>

	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
		<script type="text/javascript">
		$(document).ready(function(){
			$("#error").hide();

			$("#submit_chat").click(function(){
				if($("#chat").val() == ""){
					$("#error").show();
					$("#spanMesage").text("kosong ");
				}else{
					$("#error").hide();
					
					$("#tempatChat").append("<div class='orang'>  <span class='user'>"+ $("#chat").val() +"</span></div>");
					$("#chat").val("")
				}
				return false;
			})
		})
	</script>
	
</body>



{% endblock %}

lab_4/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="LAB 4">
<meta name="author" content="{{author}}">
<!-- bootstrap csss -->
<link 
href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" 
rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 
'css/lab_4.css' %}" />
<link rel="stylesheet" 
href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
<title>

	{% block title %} Lab 4 By {{author}} {% endblock %}
</title>
</head>
<body>
<header>
{% include "lab_4/partials/header.html" %}
</header>
<content>
{% block content %}
<!-- content goes here -->
{% endblock %}
</content>

<footer>
<!-- TODO Block Footer dan include footer.html -->
{% block footer %}
{% include "lab_4/partials/footer.html" %}
{% endblock %}
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/Javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{% static 'js/lab_4.js' %}"></script>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/Javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

lab_5/templates/lab_5.html
{% extends "layout/base.html" %}
{% block content %}
{% load static %}
<br>
<br>
<br>
<br>
<br>
<br>
<div id="lab8">
  <button onclick="facebookLogin()">Login with Facebook</button>
</div>
<script src="{% static 'js/lab_5.js' %}"></script>

{% endblock %}

lab_5/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="LAB 4">
<meta name="author" content="{{author}}">
<!-- bootstrap csss -->
<link 
href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" 
rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 
'css/lab_4.css' %}" />
<link rel="stylesheet" 
href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
<title>

	{% block title %} Lab 4 By {{author}} {% endblock %}
</title>
</head>
<body>
<header>
{% include "lab_4/partials/header.html" %}
</header>
<content>
{% block content %}
<!-- content goes here -->
{% endblock %}
</content>

<footer>
<!-- TODO Block Footer dan include footer.html -->
{% block footer %}
{% include "lab_4/partials/footer.html" %}
{% endblock %}
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/Javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{% static 'js/lab_4.js' %}"></script>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/Javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

landing_page/templates/index_lp.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/style_ex.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <title>My Experience</title>
  </head>
  <body>
    <!-- navbar -->
    
<!-- navbar -->
<section>
<!-- side bar -->
   <!-- Start Sidebar -->
   <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
  
  <a class="navbar-brand" href="/lab-1/">My Portofolio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item ">
        <a class="nav-link" href="/my_experience/">Resume </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/landing_page/">Portofolio<span class="sr-only">(current)</span></a>
      </li>    
    </ul>
  </div>
</div>
</nav>
  <div class="collapse navbar-collapse" id="sd">
   
  </div>
</nav>


<div class="row" id="body-row">
    <div id="sidebar-container" class="sidebar-expanded d-none d-md-block">
        <ul class="list-group cd" >
          <div class="img">
            <img src="{% static 'img/aku.jpg'%}" width="100" height="100" class="rounded-circle">
          </div>
           
           <small>{{nama}}</small>
           <small>{{univ}} || {{pondok}}</small>
                       
           
        </ul>
    </div> 
    <!-- End Sidebar -->

    <!-- MAIN -->

    <div class="col" id="konten">
        
        <h1>
            Karya
        </h1>
        <h3>Karya web</h3>
        <div class="row">
          <div class="col-md-6">
            <img src="{% static 'img/index.png'%}" width="500">
          </div>
          <div class="col-md-6">
            <img src="{% static 'img/dasboard.png'%}" width="500">
          </div>
          
        </div>
        <br>
        <h3>Java</h3>
        <div class="row">
          <div class="col-md-6">
            <img src="{% static 'img/java1.png'%}" width="500">
          </div>
          <div class="col-md-6">
            <img src="{% static 'img/java2.png'%}" width="500" height="400">
          </div>

        </div>

         <br>
        <h3>C++</h3>
        <div class="row">
          <div class="col-md-6">
            <img src="{% static 'img/c1.png'%}" width="500">
          </div>
          <div class="col-md-6">
            <img src="{% static 'img/c2.png'%}" width="500" height="400">
          </div>
        </div>
        <br>
        <h3>Sertifikasi keahlian</h3>
        <div class="row">
          <div class="col-md">
            <img src="{% static 'img/smos.jpg'%}" width="600">
          </div>
          


       
        
    </div>
</div>
</section>
<footer>
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <p>Copyright 2019 | by <a href="https://www.facebook.com/uzumakiaann?ref=bookmarks">Abdul Azis Ansori</a></p>
            
          </div>
          
        </div>
        
      </div>
    </footer>


    










    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}